spring.application.name=coroute
spring.datasource.url=jdbc:postgresql://localhost:5432/coroute
spring.datasource.username=mhamed
spring.datasource.password=H11g5fg65u@

spring.jpa.hibernate.ddl-auto=update
